//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAVCPigeonClockingWebsite {
    
    
    public partial class RaceResult {
        
        /// <summary>
        /// raceDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MAVCPigeonClockingWebsite.RaceDetails raceDetails;
        
        /// <summary>
        /// raceResultV1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MAVCPigeonClockingWebsite.RaceResult_V1 raceResultV1;
        
        /// <summary>
        /// raceResultV3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MAVCPigeonClockingWebsite.RaceResult_V3 raceResultV3;
    }
}
